create table if not exists
    public.ingredients (
                           id bigint generated by default as identity not null,
                           created_at timestamp with time zone not null default now(),
                           name text null,
                           quantity bigint null,
                           unit text null,
                           last_updated timestamp without time zone null,
                           constraint ingredient_pkey primary key (id),
                           constraint ingredient_id_key unique (id)
) tablespace pg_default;